### ISSUE TITLE
Design Review

### ISSUE THREAD

**Issue by matiasfha** [matiasfha/control-remoto#8]

**Comment by iamcamilo** [comment]
TO DO:

- [ ] el ancho de las secciones: Player, Playlist y About debieran tener el ancho menor que tenían antes.
- [ ] el padding bottom del footer es demasiado, disminuir
- [ ] el bg color del footer (lo que dice control remoto 2020) debiera ser color negro absoluto (#000)

**Comment by matiasfha** [comment]
Lo del ancho de las secciones quieres decir que lo baje de 720px a 648px?

--
Matías Hernández
Software/Product Engineer
My digital garden https://matiashernandez.dev
Find me on https://twitter.com/matiasfha

**Comment by iamcamilo** [comment]
no me llegan las notificaciones... weird.
exacto @matiasfha
